import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/context/AuthProvider";
import NextTopLoader from "nextjs-toploader";
import StickyIcons from "@/components/StickyIcons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rajesh Murmu | rajeshsonmurmu | Web - Developer",
  description: "Generated by create next app",
  // <!-- fontawesome script -->
  // <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
  // <script src="https://kit.fontawesome.com/ef4e39c21a.js" crossorigin="anonymous"></script>
  // <title></title>
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <NextTopLoader />
          <div className="fixed inset-0 -z-10 h-full xl:h-full w-full items-center px-5 py-24 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]"></div>
          <Navbar />
          <main className="min-h-[710px] text-white">{children}</main>
          <Toaster />
          <StickyIcons />
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
