import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Rajesh Murmu | rajeshsonmurmu | Web - Developer | Services",
  description: "Generated by create next app",
  // <!-- fontawesome script -->
  // <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
  // <script src="https://kit.fontawesome.com/ef4e39c21a.js" crossorigin="anonymous"></script>
  // <title></title>
};

export default function page() {
  return <div>Services Page</div>;
}
